### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by bounis67** [Reiko69420/GblHackdoor#3]
Hello, 
I am facing a problem. The service you provided is not working (it's just me being bad at it). I have tried to install your service on various hosting platforms multiple times, and each time I encounter the same issue, which is "HTTP ERROR 500". I don't know what to do. Can you please guide me on the steps to resolve the problem?

**Comment by Reiko69420** [comment]
Hi,
First we need to determine what is causing the issue, To do this, we need to add some lines to show error, open class/core/include.php and replace line 9,10,11 with the following:
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

Then, when you visit your website, it should provide more information about what is causing the 500 ERROR

**Comment by bounis67** [comment]
Hello, thank you for your answer, here is the error I am getting:
`Fatal error: Uncaught Error: Non-static method CSRF::isAjaxRequest() cannot be called statically in /var/www/GblHackdoor-main/core/class/include.php:82 Stack trace: #0 /var/www/GblHackdoor-main/login.php(2): include() #1 {main} thrown in /var/www/GblHackdoor-main/core/class/include.php on line 82`

moreover here is some information on the nginx config (it can come from there?)

```
server {
    listen 90;
    server_name ............;
    root /var/www/GblHackdoor-main;


    index index.html index.htm index.php;

    charset utf-8;


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by loicsmith** [comment]
I have same error
